language: python
python:
  - "3.5"

branches:
  only:
    - feature-microservice-B

install:
   - pip install -r "MicroserviceB/requirements.txt"

script: 
   - cd "MicroserviceB" && python -m unittest discover -p "*Test.py"


before_deploy:
  - cd ..
  - tar -cvzf omniDataIngestor.tar.gz MicroserviceB scripts appspec.yml Dockerfile || true
  - mkdir -p "s3_upload_dir"
  - mv omniDataIngestor.tar.gz s3_upload_dir/omniDataIngestor.tar.gz || true

deploy:
  - provider: s3
    access_key_id: $ARTIFACTS_KEY
    secret_access_key: $ARTIFACTS_SECRET
    local_dir: s3_upload_dir
    bucket: sga-team-omni
    region: us-west-2
    acl: public_read
    detect_encoding: true
    skip_cleanup: true
    on:
      repo: airavata-courses/TeamOmni
      branch: feature-microservice-B
  - provider: codedeploy
    access_key_id: $ARTIFACTS_KEY
    secret_access_key: $ARTIFACTS_SECRET
    bucket: sga-team-omni
    key: omniDataIngestor.tar.gz
    bundle_type: tgz
    application: SGA-TeamOmni
    deployment_group: SGA-TeamOmni
    region: us-east-1
    on:
      repo: airavata-courses/TeamOmni
      branch: feature-microservice-B
